CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE sighs
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          UUID         NOT NULL,
    location            geometry(Point, 4326) NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_sighs_request_id UNIQUE (request_id)
);
