CREATE TABLE sigh_reports
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigh_id            BIGINT       NOT NULL,
    reporter_device_id UUID         NOT NULL,
    reason             VARCHAR(200) NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_sigh_reports_sigh
        FOREIGN KEY (sigh_id) REFERENCES sighs (id),
    CONSTRAINT uk_sigh_reports_sigh_reporter
        UNIQUE (sigh_id, reporter_device_id)
);
