package com.classitda.studio.domain;

public enum PermissionCode {
    STUDIO_UPDATE,
    POLICY_MANAGE,
    ROOM_MANAGE,
    ROLE_MANAGE,
    MEMBER_READ,
    MEMBER_INVITE,
    MEMBER_MANAGE,
    CLASS_TYPE_MANAGE,
    CLASS_TEMPLATE_MANAGE,
    CLASS_SESSION_MANAGE_OWN,
    CLASS_SESSION_MANAGE_ALL,
    RESERVATION_READ,
    RESERVATION_MANAGE,
    PASS_PRODUCT_MANAGE,
    PASS_MEMBER_MANAGE,
    NOTICE_MANAGE
}
