SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS waiting;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS member_pass;
DROP TABLE IF EXISTS pass;
DROP TABLE IF EXISTS class_session;
DROP TABLE IF EXISTS class_template;
DROP TABLE IF EXISTS studio_membership;
DROP TABLE IF EXISTS role_permission;
DROP TABLE IF EXISTS studio_role;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS studio_policy;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS studio;
DROP TABLE IF EXISTS member_term_agreement;
DROP TABLE IF EXISTS term;
DROP TABLE IF EXISTS member;

SET FOREIGN_KEY_CHECKS = 1;
